// MHT-CET chapter lists per Class & Subject (Maharashtra State Board)
export type StudyClass = "XI" | "XII";
export type CetSubject = "Physics" | "Chemistry" | "Mathematics" | "Biology";

export const CHAPTERS: Record<StudyClass, Record<CetSubject, string[]>> = {
  XI: {
    Physics: [
      "Units and Measurements",
      "Mathematical Methods",
      "Motion in a Plane",
      "Laws of Motion",
      "Gravitation",
      "Mechanical Properties of Solids",
      "Thermal Properties of Matter",
      "Sound",
      "Optics",
      "Electrostatics",
      "Semiconductors",
    ],
    Chemistry: [
      "Some Basic Concepts of Chemistry",
      "Structure of Atom",
      "States of Matter",
      "Chemical Bonding",
      "Redox Reactions",
      "Elements of Groups 1 and 2",
      "Elements of Groups 13, 14 and 15",
      "Adsorption and Colloids",
      "Basic Principles of Organic Chemistry",
      "Hydrocarbons",
      "Chemistry in Everyday Life",
    ],
    Mathematics: [
      "Angle and its Measurement",
      "Trigonometry I",
      "Trigonometry II",
      "Determinants and Matrices",
      "Straight Line",
      "Circle",
      "Conic Sections",
      "Measures of Dispersion",
      "Probability",
      "Complex Numbers",
      "Sequences and Series",
      "Permutations and Combinations",
      "Functions",
      "Limits",
      "Continuity",
      "Differentiation",
    ],
    Biology: [
      "Diversity in Organisms",
      "Kingdom Plantae",
      "Kingdom Animalia",
      "Biochemistry of Cell",
      "Cell Division",
      "Plant Tissues and Anatomy",
      "Morphology of Flowering Plants",
      "Animal Tissues",
      "Study of Animal Type - Cockroach",
      "Photosynthesis",
      "Respiration",
      "Human Nutrition",
      "Excretion and Osmoregulation",
    ],
  },
  XII: {
    Physics: [
      "Rotational Dynamics",
      "Mechanical Properties of Fluids",
      "Kinetic Theory of Gases and Radiation",
      "Thermodynamics",
      "Oscillations",
      "Superposition of Waves",
      "Wave Optics",
      "Electrostatics",
      "Current Electricity",
      "Magnetic Fields due to Electric Current",
      "Magnetic Materials",
      "Electromagnetic Induction",
      "AC Circuits",
      "Dual Nature of Radiation and Matter",
      "Structure of Atoms and Nuclei",
      "Semiconductor Devices",
    ],
    Chemistry: [
      "Solid State",
      "Solutions",
      "Ionic Equilibria",
      "Chemical Thermodynamics",
      "Electrochemistry",
      "Chemical Kinetics",
      "Elements of Groups 16, 17 and 18",
      "Transition and Inner Transition Elements",
      "Coordination Compounds",
      "Halogen Derivatives",
      "Alcohols, Phenols and Ethers",
      "Aldehydes, Ketones and Carboxylic Acids",
      "Amines",
      "Biomolecules",
      "Introduction to Polymer Chemistry",
      "Green Chemistry and Nanochemistry",
    ],
    Mathematics: [
      "Mathematical Logic",
      "Matrices",
      "Trigonometric Functions",
      "Pair of Straight Lines",
      "Vectors",
      "Line and Plane",
      "Linear Programming",
      "Differentiation",
      "Applications of Derivatives",
      "Indefinite Integration",
      "Definite Integration",
      "Application of Definite Integration",
      "Differential Equations",
      "Probability Distributions",
      "Binomial Distribution",
    ],
    Biology: [
      "Reproduction in Lower and Higher Plants",
      "Reproduction in Lower and Higher Animals",
      "Inheritance and Variation",
      "Molecular Basis of Inheritance",
      "Origin and Evolution of Life",
      "Plant Water Relation",
      "Plant Growth and Mineral Nutrition",
      "Respiration and Circulation",
      "Control and Co-ordination",
      "Human Health and Diseases",
      "Enhancement of Food Production",
      "Biotechnology",
      "Organisms and Populations",
      "Ecosystems and Energy Flow",
      "Biodiversity, Conservation and Environmental Issues",
    ],
  },
};
